#!/usr/bin/env bash
# Configuring second web server

sudo apt update
sudo apt install nginx -y
sed -i "/listen 80 default_server;/ a \t add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
