#!/usr/bin/env bash
# Install and configure HAproxy on load balancer

sudo apt update
sudo apt install haproxy -y

echo "
frontend web-frontend
   bind *:80
   mode http
   default_backend web-backend

backend web-backend
   mode http
   balance roundrobin
   server 531512-web-01 100.26.156.161:80 check
   server 531512-web-02 18.207.139.51:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo chmod +x /etc/init.d/haproxy
sudo service haproxy restart
